name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

      - name: Run Prettier check
        run: npm run format:check

  test-api:
    runs-on: ubuntu-latest
    needs: lint-and-format
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: inventory_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/inventory_test
      E2E_USE_REAL_DB: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Wait for PostgreSQL service
        run: |
          for i in {1..30}; do
            pg_isready -h localhost -U postgres && break
            sleep 1
          done

      - name: Create test database
        env:
          PGPASSWORD: postgres
        run: |
          psql -h localhost -U postgres -tc "SELECT 1 FROM pg_database WHERE datname = 'inventory_test'" | grep -q 1 || \
          psql -h localhost -U postgres -c "CREATE DATABASE inventory_test;"

      - name: Run Prisma migrations
        run: npm --workspace apps/api run prisma:migrate:deploy

      - name: Run API tests (unit + e2e)
        run: npm --workspace apps/api test

      - name: Show PostgreSQL logs on failure
        if: failure()
        run: |
          CONTAINER_ID=$(docker ps --filter "name=postgres" -q)
          if [ -z "$CONTAINER_ID" ]; then
            CONTAINER_ID=$(docker ps --filter "name=inventory-db" -q)
          fi
          if [ -z "$CONTAINER_ID" ]; then
            echo "PostgreSQL container not found"
          else
            docker logs "$CONTAINER_ID"
          fi

  deploy-production:
    runs-on: ubuntu-latest
    needs: test-api
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    env:
      DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
      DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
      DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
      DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
      DEPLOY_PORT: ${{ secrets.DEPLOY_PORT }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create deployment .env
        run: |
          cat <<'EOF' > .env
          DATABASE_URL=${{ secrets.DEPLOY_DATABASE_URL }}
          JWT_SECRET=${{ secrets.DEPLOY_JWT_SECRET }}
          TELEGRAM_BOT_TOKEN=${{ secrets.DEPLOY_TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID=${{ secrets.DEPLOY_TELEGRAM_CHAT_ID }}
          ADMIN_SEED_EMAIL=${{ secrets.DEPLOY_ADMIN_EMAIL }}
          ADMIN_SEED_NAME=${{ secrets.DEPLOY_ADMIN_NAME }}
          ADMIN_SEED_PASSWORD=${{ secrets.DEPLOY_ADMIN_PASSWORD }}
          THROTTLE_DEFAULT_TTL=${{ secrets.DEPLOY_THROTTLE_DEFAULT_TTL }}
          THROTTLE_DEFAULT_LIMIT=${{ secrets.DEPLOY_THROTTLE_DEFAULT_LIMIT }}
          EOF
          chmod 600 .env

      - name: Prepare SSH
        run: |
          set -euo pipefail
          PORT="${DEPLOY_PORT:-22}"
          mkdir -p ~/.ssh
          ssh-keyscan -p "$PORT" "$DEPLOY_HOST" >> ~/.ssh/known_hosts
          printf '%s\n' "$DEPLOY_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Sync source to server
        run: |
          set -euo pipefail
          PORT="${DEPLOY_PORT:-22}"
          rsync -az --delete \
            -e "ssh -p $PORT" \
            --exclude ".git" \
            --exclude "node_modules" \
            ./ "$DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH/"

      - name: Compose up on remote
        run: |
          set -euo pipefail
          PORT="${DEPLOY_PORT:-22}"
          ssh -p "$PORT" "$DEPLOY_USER@$DEPLOY_HOST" "
            set -euo pipefail
            cd '$DEPLOY_PATH'
            docker compose -f infra/docker-compose.yml down --remove-orphans || true
            docker compose -f infra/docker-compose.yml pull || true
            docker compose -f infra/docker-compose.yml up -d --build
            docker compose -f infra/docker-compose.yml ps
          "

      - name: Prisma migrate & seed
        run: |
          set -euo pipefail
          PORT="${DEPLOY_PORT:-22}"
          ssh -p "$PORT" "$DEPLOY_USER@$DEPLOY_HOST" "
            set -euo pipefail
            cd '$DEPLOY_PATH'
            docker compose -f infra/docker-compose.yml exec -T api npx prisma migrate deploy
            docker compose -f infra/docker-compose.yml exec -T api npm run seed || true
          "
